#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

import subprocess

subprocess.run(["systemctl", "--user", "enable", "cs2.service"], check=True)
subprocess.run(["systemctl", "--user", "restart", "cs2.service"], check=True)
